version: '0'
services:
  server_lbl:
    build: dockerfiledsailbl/
    command: python server/server.py
    ports:
      - 40000:40000
    volumes:
      - /home/simbauser/articles_labeling:/home/jovyan/
#  client_lbl:
#    build: dockerfiledsailbl/
#    command: streamlit run aibothelper.py --server.port 30000 --browser.gatherUsageStats False
#    ports:
#      - 30000:30000
#    depends_on:
#      - server_hlp
#    volumes:
#      - /home/simbauser/articles_labeling:/home/jovyan/