version: '0'
services:
  server_lbl:
    build: dockerfiledsailbl/
    command: python server/server.py
    ports:
      - 40000:40000
    volumes:
      - /home/simbauser/articles_labeling:/home/jovyan/
  server_long_lbl:
    build: dockerfiledsailbl/
    command: python server/server_long.py long
    ports:
      - 50000:50000
    volumes:
      - /home/simbauser/articles_labeling:/home/jovyan/
  server_xlong_lbl:
    build: dockerfiledsailbl/
    command: python server/server_long.py xlong
    ports:
      - 60000:60000
    volumes:
      - /home/simbauser/articles_labeling:/home/jovyan/
  client_lbl:
    build: dockerfiledsailbl/
    command: streamlit run app/Main_page.py --server.port 30000 --browser.gatherUsageStats False --server.enableXsrfProtection false
    ports:
      - 30000:30000
    depends_on:
      - server_lbl
      - server_long_lbl
    volumes:
      - /home/simbauser/articles_labeling:/home/jovyan/